### ISSUE TITLE
Doesn't build with polkit-qt 0.113

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2423]
```
policykitlistener.cpp: In member function ‘void PolicyKitListener::fillResult()’:
policykitlistener.cpp:326:41: error: ‘class PolkitQt1::Agent::AsyncResult’ has no member named ‘setCancel’
  326 |             m_session.data()->result()->setCancel("aciton cancel");
      |                                         ^~~~~~~~~
policykitlistener.cpp:333:23: error: ‘class PolkitQt1::Agent::AsyncResult’ has no member named ‘setCancel’
  333 |             m_result->setCancel("action cancel");
      |                       ^~~~~~~~~
```

**Comment by justforlxz** [comment]
我觉得没办法抢救了，先使用这个patch吧。

[fix.zip](https://github.com/linuxdeepin/developer-center/files/8464621/fix.zip)
