### ISSUE TITLE
5.9.8 can't build on mpv 0.34.1

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2444]
```
[   51s]    59 | class QT_DEPRECATED_BEARER_MANAGEMENT Q_NETWORK_EXPORT QNetworkConfigurationManager : public QObject
[   51s]       |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_glwidget.cpp: In member function 'virtual void dmr::MpvGLWidget::initializeGL()':
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_glwidget.cpp:498:86: error: too many initializers for 'mpv_opengl_init_params'
[   51s]   498 |         mpv_opengl_init_params gl_init_params = { get_proc_address, nullptr, nullptr };
[   51s]       |                                                                                      ^
[   51s] make[2]: *** [src/CMakeFiles/deepin-movie.dir/build.make:4206: src/CMakeFiles/deepin-movie.dir/backends/mpv/mpv_glwidget.cpp.o] Error 1
[   51s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/build'
[   51s] make[2]: *** Waiting for unfinished jobs....
```

```
[   51s] /usr/include/qt5/QtNetwork/qnetworkconfigmanager.h:59:56: note: declared here
[   51s]    59 | class QT_DEPRECATED_BEARER_MANAGEMENT Q_NETWORK_EXPORT QNetworkConfigurationManager : public QObject
[   51s]       |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_proxy.cpp: In member function 'void dmr::MpvProxy::handle_mpv_events()':
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_proxy.cpp:665:14: error: 'MPV_EVENT_TRACKS_CHANGED' was not declared in this scope; did you mean 'MPV_EVENT_PROPERTY_CHANGE'?
[   51s]   665 |         case MPV_EVENT_TRACKS_CHANGED:
[   51s]       |              ^~~~~~~~~~~~~~~~~~~~~~~~
[   51s]       |              MPV_EVENT_PROPERTY_CHANGE
```

**Comment by Zeno-sole** [comment]
This is a known issue, our kwin still uses version 5.15, and these screenshot files are generated in order to realize the window preview

**Comment by tsic404** [comment]
duplicate #2250
