### ISSUE TITLE
deepin-clone can't build with new dtk >= 5.6.17

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#6000]
### SUMMARY | 问题概要

```
/build/source/app/src/main.cpp: In function 'int main(int, char**)':
/build/source/app/src/main.cpp:100:9: error: 'logger' was not declared in this scope; did you mean 'dlogger'?
  100 |         logger->registerAppender(rollingFileAppender);
      |         ^~~~~~
      |         dlogger
/build/source/app/src/main.cpp:179:5: error: 'logger' was not declared in this scope; did you mean 'dlogger'?
  179 |     logger->registerCategoryAppender("deepin.ghost", consoleAppender);
      |     ^~~~~~
      |     dlogger
/build/source/app/src/main.cpp:222:46: warning: 'DThemeManager' is deprecated [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
  222 |         window->setStyleSheet(DThemeManager::instance()->getQssForWidget("main"));

```

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin 23
```

### STEPS TO REPRODUCE | 复现步骤

https://build.deepin.com/package/show/deepin:Develop:dde/deepin-clone
