### ISSUE TITLE
Doesn't compile with KWin 5.18.4.1

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2607]
```
[ 45%] Building CXX object plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/factory.o
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur_autogen/EWIEGA46WW/moc_blur.cpp:10,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur_autogen/mocs_compilation.cpp:2:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:61:10: error: ‘void BlurEffect::paintEffectFrame(KWin::EffectFrame*, QRegion, double, double)’ marked ‘override’, but does not override
   61 |     void paintEffectFrame(EffectFrame *frame, QRegion region, double opacity, double frameOpacity) override;
      |          ^~~~~~~~~~~~~~~~
make[2]: *** [plugins/kwineffects/blur/CMakeFiles/blur.dir/build.make:83: plugins/kwineffects/blur/CMakeFiles/blur.dir/blur_autogen/mocs_compilation.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/main.cpp:21:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:61:10: error: ‘void BlurEffect::paintEffectFrame(KWin::EffectFrame*, QRegion, double, double)’ marked ‘override’, but does not override
   61 |     void paintEffectFrame(EffectFrame *frame, QRegion region, double opacity, double frameOpacity) override;
      |          ^~~~~~~~~~~~~~~~
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:22:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:61:10: error: ‘void BlurEffect::paintEffectFrame(KWin::EffectFrame*, QRegion, double, double)’ marked ‘override’, but does not override
   61 |     void paintEffectFrame(EffectFrame *frame, QRegion region, double opacity, double frameOpacity) override;
      |          ^~~~~~~~~~~~~~~~
make[2]: *** [plugins/kwineffects/blur/CMakeFiles/blur.dir/build.make:122: plugins/kwineffects/blur/CMakeFiles/blur.dir/main.o] Error 1
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp: In member function ‘QRegion BlurEffect::expand(const QRegion&) const’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:432:43: warning: ‘QVector<QRect> QRegion::rects() const’ is deprecated: Use begin()/end() instead [-Wdeprecated-declarations]
  432 |     for (const QRect &rect : region.rects()) {
      |                                           ^
In file included from /usr/include/qt/QtGui/qmatrix.h:45,
                 from /usr/include/qt/QtGui/qtransform.h:43,
                 from /usr/include/qt/QtGui/qimage.h:48,
                 from /usr/include/qt/QtGui/QImage:1,
                 from /usr/include/kwinglobals.h:25,
                 from /usr/include/kwineffects.h:29,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:24,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:22:
/usr/include/qt/QtGui/qregion.h:125:20: note: declared here
  125 |     QVector<QRect> rects() const;
      |                    ^~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp: In member function ‘void BlurEffect::uploadRegion(QVector2D*&, const QRegion&, int)’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:473:44: warning: ‘QVector<QRect> QRegion::rects() const’ is deprecated: Use begin()/end() instead [-Wdeprecated-declarations]
  473 |         for (const QRect &r : region.rects()) {
      |                                            ^
In file included from /usr/include/qt/QtGui/qmatrix.h:45,
                 from /usr/include/qt/QtGui/qtransform.h:43,
                 from /usr/include/qt/QtGui/qimage.h:48,
                 from /usr/include/qt/QtGui/QImage:1,
                 from /usr/include/kwinglobals.h:25,
                 from /usr/include/kwineffects.h:29,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:24,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:22:
/usr/include/qt/QtGui/qregion.h:125:20: note: declared here
  125 |     QVector<QRect> rects() const;
      |                    ^~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp: In member function ‘virtual void BlurEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, int)’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:539:46: warning: ‘QVector<QRect> QRegion::rects() const’ is deprecated: Use begin()/end() instead [-Wdeprecated-declarations]
  539 |     for (const QRect &rect : data.clip.rects()) {
      |                                              ^
In file included from /usr/include/qt/QtGui/qmatrix.h:45,
                 from /usr/include/qt/QtGui/qtransform.h:43,
                 from /usr/include/qt/QtGui/qimage.h:48,
                 from /usr/include/qt/QtGui/QImage:1,
                 from /usr/include/kwinglobals.h:25,
                 from /usr/include/kwineffects.h:29,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:24,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:22:
/usr/include/qt/QtGui/qregion.h:125:20: note: declared here
  125 |     QVector<QRect> rects() const;
      |                    ^~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp: In member function ‘virtual void BlurEffect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&)’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:626:40: warning: ‘QVector<QRect> QRegion::rects() const’ is deprecated: Use begin()/end() instead [-Wdeprecated-declarations]
  626 |             for (QRect r : shape.rects()) {
      |                                        ^
In file included from /usr/include/qt/QtGui/qmatrix.h:45,
                 from /usr/include/qt/QtGui/qtransform.h:43,
                 from /usr/include/qt/QtGui/qimage.h:48,
                 from /usr/include/qt/QtGui/QImage:1,
                 from /usr/include/kwinglobals.h:25,
                 from /usr/include/kwineffects.h:29,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.h:24,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/blur/blur.cpp:22:
/usr/include/qt/QtGui/qregion.h:125:20: note: declared here
  125 |     QVector<QRect> rects() const;
      |                    ^~~~~
make[2]: *** [plugins/kwineffects/blur/CMakeFiles/blur.dir/build.make:96: plugins/kwineffects/blur/CMakeFiles/blur.dir/blur.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:669: plugins/kwineffects/blur/CMakeFiles/blur.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX shared library libkwin-xcb.so
[ 47%] Built target kwin-xcb
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:24:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.h:251:18: error: ‘virtual void MultitaskingEffect::paintScreen(int, QRegion, KWin::ScreenPaintData&)’ marked ‘override’, but does not override
  251 |     virtual void paintScreen(int mask, QRegion region, ScreenPaintData &data) override;
      |                  ^~~~~~~~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp: In member function ‘void MultitaskingEffect::calculateWindowTransformationsNatural(KWin::EffectWindowList, int, KWin::WindowMotionManager&)’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:1930:21: warning: ‘void qSort(Container&) [with Container = QList<KWin::EffectWindow*>]’ is deprecated: Use std::sort [-Wdeprecated-declarations]
 1930 |     qSort(windowlist);
      |                     ^
In file included from /usr/include/qt/QtCore/qlist.h:43,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtCore/qabstractanimation.h:43,
                 from /usr/include/qt/QtCore/QtCore:6,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:22:
/usr/include/qt/QtCore/qalgorithms.h:188:46: note: declared here
  188 | QT_DEPRECATED_X("Use std::sort") inline void qSort(Container &c)
      |                                              ^~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:1930:21: warning: ‘void qSort(Container&) [with Container = QList<KWin::EffectWindow*>]’ is deprecated: Use std::sort [-Wdeprecated-declarations]
 1930 |     qSort(windowlist);
      |                     ^
In file included from /usr/include/qt/QtCore/qlist.h:43,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtCore/qabstractanimation.h:43,
                 from /usr/include/qt/QtCore/QtCore:6,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:22:
/usr/include/qt/QtCore/qalgorithms.h:188:46: note: declared here
  188 | QT_DEPRECATED_X("Use std::sort") inline void qSort(Container &c)
      |                                              ^~~~~
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp: In member function ‘void MultitaskingEffect::calculateWindowTransformationsClosest(KWin::EffectWindowList, int, KWin::WindowMotionManager&)’:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:2182:42: warning: ‘virtual int KWin::EffectWindow::desktop() const’ is deprecated [-Wdeprecated-declarations]
 2182 |     int desktop = windowlist[0]->desktop();
      |                                          ^
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.h:35,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.cpp:24:
/usr/include/kwineffects.h:2177:33: note: declared here
 2177 |     virtual int KWIN_DEPRECATED desktop() const = 0; // prefer isOnXXX()
      |                                 ^~~~~~~
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/factory.cpp:22:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.h:251:18: error: ‘virtual void MultitaskingEffect::paintScreen(int, QRegion, KWin::ScreenPaintData&)’ marked ‘override’, but does not override
  251 |     virtual void paintScreen(int mask, QRegion region, ScreenPaintData &data) override;
      |                  ^~~~~~~~~~~
[ 49%] Linking CXX executable deepin-wm-dbus
In file included from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking_autogen/EWIEGA46WW/moc_multitasking.cpp:10,
                 from /build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking_autogen/mocs_compilation.cpp:3:
/build/deepin-kwin/src/dde-kwin-5.0.14.1/plugins/kwineffects/multitasking/multitasking.h:251:18: error: ‘virtual void MultitaskingEffect::paintScreen(int, QRegion, KWin::ScreenPaintData&)’ marked ‘override’, but does not override
  251 |     virtual void paintScreen(int mask, QRegion region, ScreenPaintData &data) override;
      |                  ^~~~~~~~~~~
make[2]: *** [plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/build.make:144: plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/multitasking.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/build.make:170: plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/factory.o] Error 1
[ 49%] Built target deepin-wm-dbus
make[2]: *** [plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/build.make:131: plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/multitasking_autogen/mocs_compilation.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:777: plugins/kwineffects/multitasking/CMakeFiles/multitasking.dir/all] Error 2
```

**Comment by justforlxz** [comment]
已经处理过了。但kwin又动了接口……
