### ISSUE TITLE
deepin-screen-recorder 5.10.15 build failure on openSUSE

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#3035]
```
[  156s] In file included from main.cpp:24:
[  156s] main_window.h:528:37: error: 'PixMergeThread' has not been declared
[  156s]   528 |     void onScrollShotMerageImgState(PixMergeThread::MergeErrorValue state);
[  156s]       |                                     ^~~~~~~~~~~~~~
[  156s] main_window.h:528:69: error: expected ',' or '...' before 'state'
[  156s]   528 |     void onScrollShotMerageImgState(PixMergeThread::MergeErrorValue state);
[  156s]       |                                                                     ^~~~~
[  156s] main_window.h:636:31: error: 'PreviewWidget' has not been declared
[  156s]   636 |     void scrollShotGrabPixmap(PreviewWidget::PostionStatus previewPostion, int direction, int mosueTime = 0);
[  156s]       |                               ^~~~~~~~~~~~~
[  156s] main_window.h:636:60: error: expected ',' or '...' before 'previewPostion'
[  156s]   636 |     void scrollShotGrabPixmap(PreviewWidget::PostionStatus previewPostion, int direction, int mosueTime = 0);
[  156s]       |                                                            ^~~~~~~~~~~~~~
[  156s] main_window.h:737:5: error: 'ScrollShotTip' does not name a type; did you mean 'ScrollShotType'?
[  156s]   737 |     ScrollShotTip *m_scrollShotTip = nullptr;
[  156s]       |     ^~~~~~~~~~~~~
[  156s]       |     ScrollShotType
[  156s] main_window.h:747:5: error: 'PreviewWidget' does not name a type; did you mean 'QTreeWidget'?
[  156s]   747 |     PreviewWidget::PostionStatus m_previewPostion = PreviewWidget::PostionStatus::RIGHT;
[  156s]       |     ^~~~~~~~~~~~~
[  156s]       |     QTreeWidget
[  156s] main_window.h: In destructor 'virtual MainWindow::~MainWindow()':
[  156s] main_window.h:221:13: error: 'm_scrollShotTip' was not declared in this scope; did you mean 'm_scrollShotType'?
[  156s]   221 |         if (m_scrollShotTip) {
[  156s]       |             ^~~~~~~~~~~~~~~
[  156s]       |             m_scrollShotType
[  156s] main_window.h:222:20: error: type '<type error>' argument given to 'delete', expected pointer
[  156s]   222 |             delete m_scrollShotTip;
[  156s]       |                    ^~~~~~~~~~~~~~~
[  156s] main_window.h:229:13: error: 'm_previewWidget' was not declared in this scope; did you mean 'topLevelWidget'?
[  156s]   229 |         if (m_previewWidget) {
[  156s]       |             ^~~~~~~~~~~~~~~
[  156s]       |             topLevelWidget
[  156s] main_window.h:230:20: error: type '<type error>' argument given to 'delete', expected pointer
[  156s]   230 |             delete m_previewWidget;
[  156s]       |                    ^~~~~~~~~~~~~~~
[  156s] make[1]: *** [Makefile:1755: main.o] Error 1
[  156s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-screen-recorder-5.10.15/src'
[  156s] make: *** [Makefile:49: sub-src-make_first] Error 2
[  156s] make: *** Waiting for unfinished jobs....
[  158s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/deepin-screen-recorder-5.10.15/src/pin_screenshots'
```

**Comment by felixonmars** [comment]
Also reproduced on Arch.

Turns out this project invented its own wheel to detect community version and thus fails on any other distros.

I have applied a simple workaround as their PR review seems stale: `sed -i "s^cat /etc/os-version | grep 'Community'^echo 'Community'^" src/src.pro`

**Comment by felixonmars** [comment]
Problem introduced in https://github.com/linuxdeepin/deepin-screen-recorder/commit/41690832343b408e9570239219c0e38c5b8b8ead#diff-8310d23bea2503c1376ea3fc7c3729f8b1add8945d25169b1ad554ba250a98baR10
