### ISSUE TITLE
Bug report 「缺陷报告」deepin-movie 5.9.8 can't build on mpv 0.34.1

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2250]
```
[   51s]    59 | class QT_DEPRECATED_BEARER_MANAGEMENT Q_NETWORK_EXPORT QNetworkConfigurationManager : public QObject
[   51s]       |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_glwidget.cpp: In member function 'virtual void dmr::MpvGLWidget::initializeGL()':
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_glwidget.cpp:498:86: error: too many initializers for 'mpv_opengl_init_params'
[   51s]   498 |         mpv_opengl_init_params gl_init_params = { get_proc_address, nullptr, nullptr };
[   51s]       |                                                                                      ^
[   51s] make[2]: *** [src/CMakeFiles/deepin-movie.dir/build.make:4206: src/CMakeFiles/deepin-movie.dir/backends/mpv/mpv_glwidget.cpp.o] Error 1
[   51s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/build'
[   51s] make[2]: *** Waiting for unfinished jobs....
```

```
[   51s] /usr/include/qt5/QtNetwork/qnetworkconfigmanager.h:59:56: note: declared here
[   51s]    59 | class QT_DEPRECATED_BEARER_MANAGEMENT Q_NETWORK_EXPORT QNetworkConfigurationManager : public QObject
[   51s]       |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_proxy.cpp: In member function 'void dmr::MpvProxy::handle_mpv_events()':
[   51s] /home/abuild/rpmbuild/BUILD/deepin-movie-reborn-5.9.8/src/backends/mpv/mpv_proxy.cpp:665:14: error: 'MPV_EVENT_TRACKS_CHANGED' was not declared in this scope; did you mean 'MPV_EVENT_PROPERTY_CHANGE'?
[   51s]   665 |         case MPV_EVENT_TRACKS_CHANGED:
[   51s]       |              ^~~~~~~~~~~~~~~~~~~~~~~~
[   51s]       |              MPV_EVENT_PROPERTY_CHANGE
```

**Comment by tsic404** [comment]
The latest mpv has remove this [MPV_EVENT_TRACKS_CHANGED](https://github.com/mpv-player/mpv/commit/f9fd50c6546f2fa510251267d6423d3f342ca115#diff-b670fdb7c79e8d76f9a053339e2ed30ac9a9592769159c148732d6fbcbfa4793L1277) while it use a inner [MP_EVENT_TRACKS_CHANGED](https://github.com/mpv-player/mpv/commit/f9fd50c6546f2fa510251267d6423d3f342ca115#diff-830516050a5bf883d9c265fa0cf3c5b59d23d8bc9e6dec63db3d3d9b9868bb6bL3798) for itself.

**Comment by hillwoodroc** [comment]
Replacing MPV_EVENT_TRACKS_CHANGED with MP_EVENT_TRACKS_CHANGED is not useful. Need help from upstream.

**Comment by tsic404** [comment]
Does [justforlxz](https://github.com/justforlxz)'s [patch](https://github.com/linuxdeepin/developer-center/issues/2233) works ?

**Comment by hillwoodroc** [comment]
No, that patch does not fix this issue.

**Comment by tsic404** [comment]
opensuse use mpv master code? Those are still reminded in [0.34.1](https://github.com/mpv-player/mpv/releases/tag/v0.34.1)

**Comment by hillwoodroc** [comment]
https://build.opensuse.org/package/show/openSUSE%3AFactory/mpv
It seems that thay use master branch.

**Comment by hillwoodroc** [comment]
This patch can workaround the first issue.
[drop-MPV_EVENT_TRACKS_CHANGED.zip](https://github.com/linuxdeepin/developer-center/files/8490003/drop-MPV_EVENT_TRACKS_CHANGED.zip)
